---
  - name: Install Python packages from pypi
    pip: name={{ item.name }} version={{ item.version }}
    with_items: python_packages
    sudo: yes

  - name: Install Python packages from repository
    pip: name={{ item }}
    with_items: python_packages_repo
    sudo: yes
