---
  - name: Install Python packages from pypi
    pip: name={{ item.name }} version={{ item.version }}
    with_items: "{{ python_packages }}"
    become: true

  - name: Install Python packages from repository
    pip: name={{ item }}
    with_items: "{{ python_packages_repo }}"
    become: true
